import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const escape = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const money = (value, currency = 'CNY') => value == null ? '价格待确认' : `${currency === 'CNY' ? '¥' : `${currency} `}${Number(value).toLocaleString('zh-CN')}`;
function card(kind, item) {
  if (kind === 'flights') return `<article><div class="tag">机票 · ${escape(item.airline || '航空公司待确认')}</div><h2>${escape(item.departure_time || '—')} <span>→</span> ${escape(item.arrival_time || '—')}</h2><p>${escape(item.departure_airport || '出发机场')} · ${escape(item.arrival_airport || '到达机场')}</p><footer><b>${money(item.price, item.currency)}</b><small>${escape(item.cabin || '舱位待确认')} ${item.flight_no ? `· ${escape(item.flight_no)}` : ''}</small>${item.source_url ? `<a href="${escape(item.source_url)}" target="_blank" rel="noreferrer">携程查看 ↗</a>` : ''}</footer></article>`;
  if (kind === 'trains') return `<article><div class="tag">${escape(item.train_type || '列')} 车 · ${escape(item.train_no || '车次待确认')}</div><h2>${escape(item.departure_time || '—')} <span>→</span> ${escape(item.arrival_time || '—')}</h2><p>${escape(item.departure_station || '出发站')} · ${escape(item.arrival_station || '到达站')}</p><footer><b>${money(item.from_price, item.currency)}</b><small>${escape(item.duration || '时长待确认')} · ${escape(item.seat_availability || '余票待确认')}</small>${item.source_url ? `<a href="${escape(item.source_url)}" target="_blank" rel="noreferrer">携程查看 ↗</a>` : ''}</footer></article>`;
  return `<article><div class="tag">${item.star ? '★'.repeat(Math.min(item.star, 5)) : '酒店'} · ${escape(item.district || item.city_name || '')}</div><h2>${escape(item.name || '酒店名称待确认')}</h2><p>${escape(item.address || '地址待确认')}</p><footer><b>${money(item.price, item.currency)}<small>/晚起</small></b><small>${item.score != null ? `${escape(item.score)} 分 · ` : ''}${item.review_count ? `${escape(item.review_count)} 条点评` : '评分待确认'}</small>${item.source_url ? `<a href="${escape(item.source_url)}" target="_blank" rel="noreferrer">携程查看 ↗</a>` : ''}</footer></article>`;
}
export async function writeCtripReport(kind, data) {
  const title = { flights: '机票方案', trains: '列车方案', hotels: '住宿方案' }[kind] || '旅行方案';
  const query = Object.entries(data.query || {}).filter(([, value]) => value != null && value !== '').map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join('/') : value}`).join(' · ');
  const cards = (data.results || []).map((item) => card(kind, item)).join('') || '<div class="empty">这次查询没有符合条件的结果。</div>';
  const note = data.note ? `<aside>${escape(data.note)}</aside>` : '';
  const html = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}｜旅行助手</title><style>:root{font-family:Inter,-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;color:#17233a;background:#f5f7fb}*{box-sizing:border-box}body{margin:0;padding:40px 20px;background:radial-gradient(circle at 15% 0,#dceaff,transparent 35%),#f5f7fb}main{max-width:940px;margin:auto}.eyebrow,.tag{color:#3268d6;font-weight:800;font-size:12px;letter-spacing:.12em;text-transform:uppercase}h1{font-size:clamp(32px,6vw,58px);letter-spacing:-.06em;margin:8px 0}header>p{color:#67748a;line-height:1.6}header{margin-bottom:28px}section{display:grid;gap:14px}article{background:#fff;border:1px solid #e2e8f2;border-radius:18px;padding:22px 24px;box-shadow:0 12px 30px #26385d0c}h2{font-size:24px;margin:9px 0 6px;letter-spacing:-.035em}h2 span{color:#7194e6;margin:0 7px}article p{margin:0;color:#64748b}footer{display:flex;align-items:center;gap:13px;flex-wrap:wrap;border-top:1px solid #edf0f6;margin-top:17px;padding-top:14px}footer b{font-size:20px;color:#e75a2e}footer b small,footer>small{font-size:13px;font-weight:500;color:#718096}a{margin-left:auto;color:#2767cf;text-decoration:none;font-size:14px;font-weight:700}aside,.empty{background:#fff7e8;border:1px solid #fde0aa;color:#8a601c;border-radius:12px;padding:14px 16px;font-size:14px;margin-top:18px}.meta{font-size:13px;color:#7d899c}@media(max-width:520px){body{padding:25px 14px}article{padding:19px}a{margin-left:0;width:100%}}</style><main><header><p class="eyebrow">CTRIP · OPENCLI · READ ONLY</p><h1>${escape(title)}</h1><p>${escape(query || '实时查询')}<br><span class="meta">查询于 ${escape(data.queried_at || new Date().toISOString())} · 价格与余票可能随时变化</span></p></header><section>${cards}</section>${note}</main></html>`;
  const file = path.resolve('output/ctrip-report.html'); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, html); return { htmlFile: file };
}

export async function writeCtripItineraryReport(sections) {
  const labels = { flights: '航班候选', trains: '高铁 / 动车候选', hotels: '住宿候选' };
  const content = sections.map(({ kind, data }) => `<section><h2 class="section-title">${labels[kind]}</h2>${(data.results || []).map((item) => card(kind, item)).join('') || '<div class="empty">未返回符合条件的结果。</div>'}</section>`).join('');
  const queries = sections.map(({ data }) => Object.entries(data.query || {}).filter(([, value]) => value != null && value !== '').map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join('/') : value}`).join(' · ')).join(' &nbsp; | &nbsp; ');
  const generatedAt = sections.map(({ data }) => data.queried_at).filter(Boolean).sort().at(-1) || new Date().toISOString();
  const html = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>携程旅行方案｜旅行助手</title><style>:root{font-family:Inter,-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;color:#17233a;background:#f5f7fb}*{box-sizing:border-box}body{margin:0;padding:40px 20px;background:radial-gradient(circle at 15% 0,#dceaff,transparent 35%),#f5f7fb}main{max-width:940px;margin:auto}.eyebrow,.tag{color:#3268d6;font-weight:800;font-size:12px;letter-spacing:.12em;text-transform:uppercase}h1{font-size:clamp(32px,6vw,58px);letter-spacing:-.06em;margin:8px 0}header>p{color:#67748a;line-height:1.6}header{margin-bottom:28px}section{display:grid;gap:14px;margin-top:34px}.section-title{font-size:20px;margin:0 0 2px;letter-spacing:-.03em}article{background:#fff;border:1px solid #e2e8f2;border-radius:18px;padding:22px 24px;box-shadow:0 12px 30px #26385d0c}article h2{font-size:24px;margin:9px 0 6px;letter-spacing:-.035em}article h2 span{color:#7194e6;margin:0 7px}article p{margin:0;color:#64748b}footer{display:flex;align-items:center;gap:13px;flex-wrap:wrap;border-top:1px solid #edf0f6;margin-top:17px;padding-top:14px}footer b{font-size:20px;color:#e75a2e}footer b small,footer>small{font-size:13px;font-weight:500;color:#718096}a{margin-left:auto;color:#2767cf;text-decoration:none;font-size:14px;font-weight:700}.empty{background:#fff7e8;border:1px solid #fde0aa;color:#8a601c;border-radius:12px;padding:14px 16px;font-size:14px}.meta{font-size:13px;color:#7d899c}@media(max-width:520px){body{padding:25px 14px}article{padding:19px}a{margin-left:0;width:100%}}</style><main><header><p class="eyebrow">CTRIP · OPENCLI · READ ONLY</p><h1>旅行交通与住宿查询结果</h1><p>${queries}<br><span class="meta">查询于 ${escape(generatedAt)} · 价格与余票可能随时变化</span></p></header>${content}</main></html>`;
  const file = path.resolve('output/ctrip-live-demo.html'); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, html); return { htmlFile: file };
}
